In [27]:
from pathlib import Path
import pandas as pd

In [28]:
# Store filepath in a variable
file = Path("Resources/user_behavior_dataset.csv")

In [29]:
# Read our data file with the Pandas library
original_df = pd.read_csv(file)
original_df.head()

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
0,1,Google Pixel 5,Android,393,6.4,1872,67,1122,40,Male,4
1,2,OnePlus 9,Android,268,4.7,1331,42,944,47,Female,3
2,3,Xiaomi Mi 11,Android,154,4.0,761,32,322,42,Male,2
3,4,Google Pixel 5,Android,239,4.8,1676,56,871,20,Male,3
4,5,iPhone 12,iOS,187,4.3,1367,58,988,31,Female,3

In [30]:
original_df.columns

Index(['User ID', 'Device Model', 'Operating System',
       'App Usage Time (min/day)', 'Screen On Time (hours/day)',
       'Battery Drain (mAh/day)', 'Number of Apps Installed',
       'Data Usage (MB/day)', 'Age', 'Gender', 'User Behavior Class'],
      dtype='object')

In [31]:
columns_list = original_df.columns.tolist() 
columns_list

['User ID',
 'Device Model',
 'Operating System',
 'App Usage Time (min/day)',
 'Screen On Time (hours/day)',
 'Battery Drain (mAh/day)',
 'Number of Apps Installed',
 'Data Usage (MB/day)',
 'Age',
 'Gender',
 'User Behavior Class']

In [32]:
labels = [col.replace(' ', '_') for col in original_df.columns]

labels_lower = [item.lower() for item in labels]

labels_lower

['user_id',
 'device_model',
 'operating_system',
 'app_usage_time_(min/day)',
 'screen_on_time_(hours/day)',
 'battery_drain_(mah/day)',
 'number_of_apps_installed',
 'data_usage_(mb/day)',
 'age',
 'gender',
 'user_behavior_class']

In [35]:
columns_dict = dict(zip(columns_list, labels_lower))
columns_dict

{'User ID': 'user_id',
 'Device Model': 'device_model',
 'Operating System': 'operating_system',
 'App Usage Time (min/day)': 'app_usage_time_(min/day)',
 'Screen On Time (hours/day)': 'screen_on_time_(hours/day)',
 'Battery Drain (mAh/day)': 'battery_drain_(mah/day)',
 'Number of Apps Installed': 'number_of_apps_installed',
 'Data Usage (MB/day)': 'data_usage_(mb/day)',
 'Age': 'age',
 'Gender': 'gender',
 'User Behavior Class': 'user_behavior_class'}

In [47]:
columns_dict_new = {'User ID': 'user_id',
 'Device Model': 'device_model',
 'Operating System': 'operating_system',
 'App Usage Time (min/day)': 'app_usage_minutes_per_day',
 'Screen On Time (hours/day)': 'screen_time_hours_per_day',
 'Battery Drain (mAh/day)': 'battery_drain_mah_per_day',
 'Number of Apps Installed': 'number_of_apps_installed',
 'Data Usage (MB/day)': 'data_usage_mb_per_day',
 'Age': 'age',
 'Gender': 'gender',
 'User Behavior Class': 'user_behavior_class'}

In [48]:
df_columns_final = original_df.rename(columns=columns_dict_new)
df_columns_final

,user_id,device_model,operating_system,app_usage_minutes_per_day,screen_time_hours_per_day,battery_drain_mah_per_day,number_of_apps_installed,data_usage_mb_per_day,age,gender,user_behavior_class
0,1,Google Pixel 5,Android,393,6.4,1872,67,1122,40,Male,4
1,2,OnePlus 9,Android,268,4.7,1331,42,944,47,Female,3
2,3,Xiaomi Mi 11,Android,154,4.0,761,32,322,42,Male,2
3,4,Google Pixel 5,Android,239,4.8,1676,56,871,20,Male,3
4,5,iPhone 12,iOS,187,4.3,1367,58,988,31,Female,3
...,...,...,...,...,...,...,...,...,...,...,...
695,696,iPhone 12,iOS,92,3.9,1082,26,381,22,Male,2
696,697,Xiaomi Mi 11,Android,316,6.8,1965,68,1201,59,Male,4
697,698,Google Pixel 5,Android,99,3.1,942,22,457,50,Female,2
698,699,Samsung Galaxy S21,Android,62,1.7,431,13,224,44,Male,1
699,700,OnePlus 9,Android,212,5.4,1306,49,828,23,Female,3

In [49]:
df_columns_final.to_csv('data.csv', index=False)